#!/usr/bin/env python3
"""
Fix protobuf generated files to work with heyhi.

This script inspects and fixes protobuf generated files to make them
compatible with the heyhi module.
"""
import os
import sys
import glob
import re

def print_header(title):
    """Print a section header."""
    print(f"\n{'=' * 60}")
    print(f" {title}")
    print(f"{'=' * 60}")

def print_success(msg):
    """Print a success message."""
    print(f"✅ {msg}")

def print_error(msg):
    """Print an error message."""
    print(f"❌ {msg}")

def print_warning(msg):
    """Print a warning message."""
    print(f"⚠️ {msg}")

# Define the project paths
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
conf_dir = os.path.join(project_root, "conf")
heyhi_dir = os.path.join(project_root, "heyhi")

print_header("PROTOBUF FILE FIXER")
print(f"Project root: {project_root}")
print(f"Looking for protobuf files in: {conf_dir}")

# Ensure the conf directory exists
if not os.path.isdir(conf_dir):
    print_error(f"Conf directory not found: {conf_dir}")
    sys.exit(1)

# Check for protobuf Python files
pb2_files = glob.glob(os.path.join(conf_dir, "*_pb2.py"))
if not pb2_files:
    print_error(f"No protobuf Python files found in {conf_dir}")
    print_warning("You need to run 'make protos_basic' first")
    sys.exit(1)

print_success(f"Found {len(pb2_files)} protobuf Python files")

# Check for conf_cfgs.py
conf_cfgs_path = os.path.join(conf_dir, "conf_cfgs.py")
if not os.path.exists(conf_cfgs_path):
    print_warning(f"conf_cfgs.py not found, will create it")
else:
    print_success(f"Found conf_cfgs.py")

# Fix conf_cfgs.py or create it if it doesn't exist
with open(conf_cfgs_path, "w") as f:
    f.write("""#!/usr/bin/env python3
# Generated with fix_proto_for_heyhi.py
import sys
import os

# Create empty symbol table to make imports work
FROZEN_SYM_BD = {'fairdiplomacy.MetaCfg': None}

# Import all protobuf modules
from conf import agents_pb2
from conf import common_pb2
from conf import conf_pb2
from conf import misc_pb2

# Create simplified mapping
class Config:
    pass

# Export Config class
sys.modules['fairdiplomacy.MetaCfg'] = Config
""")

print_success(f"Created/updated conf_cfgs.py")

# Check or fix heyhi/conf.py if needed
heyhi_conf_path = os.path.join(heyhi_dir, "conf.py")
if os.path.exists(heyhi_conf_path):
    with open(heyhi_conf_path, "r") as f:
        conf_content = f.read()
    
    # Check if FROZEN_SYM_BD is used without definition
    if "FROZEN_SYM_BD" in conf_content and "FROZEN_SYM_BD = " not in conf_content:
        print_warning(f"heyhi/conf.py uses FROZEN_SYM_BD but doesn't define it, will fix")
        
        # Add import for conf_cfgs if needed
        if "import conf.conf_cfgs" not in conf_content:
            conf_content = re.sub(
                r"import os(\s+)",
                r"import os\1import conf.conf_cfgs\1from conf.conf_cfgs import FROZEN_SYM_BD\1",
                conf_content
            )
            
            # Write the modified file
            with open(heyhi_conf_path, "w") as f:
                f.write(conf_content)
            
            print_success(f"Fixed heyhi/conf.py to import FROZEN_SYM_BD")
        else:
            print_success(f"heyhi/conf.py already imports conf_cfgs")
    else:
        print_success(f"heyhi/conf.py doesn't use FROZEN_SYM_BD or already defines it")
else:
    print_error(f"heyhi/conf.py not found, something is wrong with the installation")
    sys.exit(1)

# Create Python package markers if needed
for dir_path in [conf_dir, heyhi_dir]:
    init_file = os.path.join(dir_path, "__init__.py")
    if not os.path.exists(init_file):
        with open(init_file, "w") as f:
            f.write("# Generated by fix_proto_for_heyhi.py\n")
        print_success(f"Created missing __init__.py in {os.path.relpath(dir_path, project_root)}")

print_header("PROTOBUF FIX COMPLETE")
print_success("All protobuf files have been fixed")
print("You should now be able to import heyhi")
print("If you still encounter issues, try recompiling the protobuf files with:")
print("  make protos_basic")
print("And then run this script again.")